server:
  port: 9192
spring.datasource.url=jdbc:mysql://localhost:3306/demo
  config:    import: configserver:http://localhost:8888
  application:
    name: ORDER-SERVICE
        
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost